### ISSUE TITLE
Renter's Insurance - Enrolling, Charging, and Tracking Residents

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#317]
Madera is recrafting its Renter's Insurance lease addendum to inform applicants that:

- They have to have renters insurance
- They can allow us to enroll them into ours and we'll make things easy on them
- Or they can go get their own 3rd party and  they'll have to show us proof of insurance

[Here is the old Addendum. ](https://drive.google.com/drive/u/0/folders/1S_ITLKqtOlPwlCLzOTnmCtVvN5IEKitU) The new one will be similar.  Key clauses are 1e, 2a, and 2b.

Among other requirements, we will need the following things in place for Renter's Insurance

- [ ] Each Resident record needs to capture what insurance company is providing their renter's insurance
- [ ] The leasing agent needs to be able to input this information (probably in Person Detailed Settings)
- [ ] The leasing agent needs to be able to input the expiration date for the policy
- [ ] If they elect to use Madera's captive insurance, we would call that Captive
- [ ] If they elect to use Captive, there are two options:  Plan A (Liability Only) and Plan B (Personal Property)
- [ ] We need to establish the standard costs of Plans A & B in our Global Standard Fees section.  Plan A is $10/month.  Plan B is $15/month
- [ ] The leasing agent needs to be able to assign a $50 one time charge to the resident for "Late Enrollment" if the resident does not have proof of insurance the day they move in. 
- [ ] The leasing agent needs to be able to say whether they had to force place a resident into our insurance
- [ ] We need to trigger an automatic notification to the resident and alert the leasing office 30 days prior to  HO4 insurance policy expiration date.
- [ ] If resident moves in on or before the 20th, they will pay full amount for insurance if 21st or later free for that month.
